Add dropzone
theodorusclarence/rhf-stepform pull request #1
Opened 2021-08-08 15:12 UTC by rizqitsani

- Yang di recap belum dikerjain, kayanya bisa dibuat image gallery gitu aja, cuma belum ada filenya
- Type StepTwoData bisa dibuat FileWithPath[] cuma yup jadi error

2021-08-08 15:17 UTC, theodorusclarence requested changes

2021-08-08 15:17 UTC, theodorusclarence commented on components/Forms/DropzoneInput.tsx
> +            onClick={() => setIsOpen(true)}
type button yang ini jangan lupa riz

2021-08-08 15:17 UTC, theodorusclarence commented on pages/form/step-2.tsx
> +                  maxFiles={3}
maxFiles dibikin 1 aja gapapa riz, 

biasanya kalo ada beberapa file, 1 1 inputnya wkwkwkwk,

2021-08-08 15:17 UTC, theodorusclarence commented
footer jangan lupa tambahin

2021-08-08 15:18 UTC, theodorusclarence commented on components/Forms/DropzoneInput.tsx
> +import { classNames } from '@/lib/helper';
oh sama ini, pake clsx aja riz, uda migrate gw wkwkwkwk

`import clsx from 'clsx'`

cara pakenya sama persis, ganti nama aja

2021-08-08 15:19 UTC, theodorusclarence commented on components/Forms/DropzoneInput.tsx
> +  readonly?: boolean;
sama ini, kayaknya mending pake `readOnly` biar konsisten sama yang lain

2021-08-08 15:20 UTC, rizqitsani commented on pages/form/step-2.tsx
> +                  maxFiles={3}
okee wkwk

2021-08-08 15:20 UTC, rizqitsani commented on components/Forms/DropzoneInput.tsx
> +  readonly?: boolean;
typo :)

2021-08-09 04:55 UTC, theodorusclarence commented
#### 📝Changed routes:


| [**/form/step-2**](https://rhf-stepform-9zgxlkwep-theodorusclarence.vercel.app/form/step-2) | [**/**](https://rhf-stepform-9zgxlkwep-theodorusclarence.vercel.app/) |
|:-:|:-:|
|<a href="https://rhf-stepform-9zgxlkwep-theodorusclarence.vercel.app/form/step-2"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/UqF6yOUOsJfULA90DU3f4tyrNhopPRAixF6JtlkYWbmPI0eXvB0FkykJfomK1qbm8I2VD2HekNel2cF_RTnL1g.png&w=600" alt="Screenshot of /form/step-2" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/hc3w6w-xLHP81D5zz_TEO8ILguHashjJFE4lE8N95a9D6X887kjZl1xq5RDexu6A9HeKouBapZpKichUAtneJg.png">(view full size)</a> |<a href="https://rhf-stepform-9zgxlkwep-theodorusclarence.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/C2bgsmPOWkTw6-7zPrdNUXGOkj6t6YdTO7Bx33b_A-WyS6cVntu9t_UlDoXJ1Ye7p8F1tpk9pJDmAQWVuQ12YA.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/PCsJiy-J7JU6_iYLJGSmaAl7ip10-HNneQOkSJ6iZP3qsx7wuu1yEXe4ItJC_fcBSrryn1N1WIUWcRRzwCLZDQ.png">(view full size)</a> |







Commit 40a26e539252fd31d85b6641615a0c9083df595c (https://rhf-stepform-9zgxlkwep-theodorusclarence.vercel.app).

2021-08-09 05:09 UTC, theodorusclarence commented on pages/form/step-2.tsx
>                    helperText='You can only drop .jpg, .jpeg, and .png image here'
helper text jangan lupa wkwkwk

2021-08-09 05:28 UTC, theodorusclarence commented on components/Forms/DropzoneInput.tsx
>        {file.name}
https://github.com/theodorusclarence/rhf-stepform/pull/1/commits/40a26e539252fd31d85b6641615a0c9083df595c#diff-c0ee6be7eeffa2e5387b467184179e3550c4ebc7351dd7e7d21ac41062d1f515R50-R56

yang ini iconsnya tetep pake aja gimana?
mungkin yang image -> pake icon HiOutlinePhotograph
sisanya pake paper clip

2021-08-09 05:40 UTC, theodorusclarence commented on components/Forms/DropzoneInput.tsx
> +            className='text-gray-500 cursor-pointer hover:text-gray-700'
cursor-pointer apus ajaa

2021-08-09 05:44 UTC, theodorusclarence approved these changes
![image](https://user-images.githubusercontent.com/55318172/128443957-9129c657-ff69-42a3-b3c5-96417ad076e8.png)

2021-08-09 05:44 UTC, merged